### ISSUE TITLE
Map cache to shard to allow per-shard invalidation where possible

### ISSUE THREAD

**Issue by queer** [mewna/catnip#106]
Right now, caching is done globally rather than per-shard. This is nice because it allows for deduping cache, but is an issue in that it doesn't allow for invalidating parts of the cache when a shard goes down.

**Comment by natanbc** [comment]
Most caches (guilds, members, roles, guild channels, emojis, voice states) could easily be purged by guild id, but users, presences and dm channels have no easy way of cleaning without iterating the whole cache. Maybe we could have per-shard caches and use `CompositeCacheView`s for those 3 instead?

**Comment by natanbc** [comment]
Fixed in #158
