### ISSUE TITLE
Add utility method to search the cache without creating a full copy

### ISSUE THREAD

**Issue by natanbc** [mewna/catnip#123]
Currently, searching the cache for an entity matching an arbitrary filter (not id) requires [a full copy](https://github.com/mewna/catnip/blob/63eabf1378adebc5af91991a0095ce4446440ddb/src/main/java/com/mewna/catnip/cache/MemoryEntityCache.java#L435-L448), which may be undesirable. Since all caches are [thread safe](https://github.com/mewna/catnip/blob/63eabf1378adebc5af91991a0095ce4446440ddb/src/main/java/com/mewna/catnip/cache/MemoryEntityCache.java#L72-L87), it would be possible to add methods that find based on a provided Predicate, returning the matched entities.

For example:
```java
List<Member> findMembers(String guildId, Predicate<Member> filter);

List<Member> findMembersByName(String guildId, String name, boolean ignoreCase);

List<User> findUsers(Predicate<User> filter);

List<User> findUsersByName(String name, boolean ignoreCase);
```

Similar methods would also be created for other types of entities.

**Comment by queer** [comment]
Fixed in #124
