### ISSUE TITLE
Detect if the shard websocket was closed by the client or the server

### ISSUE THREAD

**Issue by queer** [mewna/catnip#173]
Right now, we have this code that shows what reason the websocket closed with

https://github.com/mewna/catnip/blob/3c60f23702a8e10995b8f9d2d42ac809c6bafdb6/src/main/java/com/mewna/catnip/shard/CatnipShard.java#L337-L349

But we also close the websocket with specific code ourselves, eg.

https://github.com/mewna/catnip/blob/3c60f23702a8e10995b8f9d2d42ac809c6bafdb6/src/main/java/com/mewna/catnip/shard/CatnipShard.java#L253-L261

which is then logged like a server-side close

**Comment by queer** [comment]
When we're closing the socket we can just set a flag on the shard class that's cleared when we open another connection

**Comment by SamOphis** [comment]
yea, that'd be good actually
