### ISSUE TITLE
Rewrite CachingBuffer

### ISSUE THREAD

**Issue by queer** [mewna/catnip#179]
It's a mess, none of us understand it anymore apparently, so just fix it

**Comment by natanbc** [comment]
`rm -rf CachingBuffer.java && <your favorite editor> CachingBuffer.java`

**Comment by SamOphis** [comment]
This seems like an issue the very experienced SamOphis can handle. 👍

**Comment by queer** [comment]
I'll close this for now as I think it should be more understandable as of bc59a2f, but we'll see.
