### ISSUE TITLE
Remove/Replace/Clear Fields on EmbedBuilder

### ISSUE THREAD

**Issue by adriantodt** [mewna/catnip#203]
Ability to replace and remove already added fields on EmbedBuilder

Due to the way some calculations can be relatively expensive to do, to keep user experience at best, I first send an embed with all the data that is easily gatherable, send it, then start the expensive stuff and replace the "placeholder field" with the data.

Eg:

```java
EmbedBuilder builder = ...;

// author, footer, color goes here

builder.field("Stats:", "Gathering... Please Wait", true);

sentMessage = message.channel().sendMessage(builder.build());

// calculate dumb stuff like "size of all music queues"

// remove the placeholder field. in JDA that was smth like this:
builder.fields.remove(builder.fields.last());

sentMessage.thenCompose((m) -> m.edit(builder.build()));
```

Also suggestion to be add `builder.clearFields()` as well

**Comment by SamOphis** [comment]
this one's a little hard to implement and would also be incredibly inefficient by using `fields()`, as that generates a new immutableset each time it's called.

we should ideally add internal methods to the EmbedBuilder that do this without generating a bunch of immutable sets. it's also inefficient to remove and access from lists so it should be used sparingly (and we should emphasize that in documentation too)
