### ISSUE TITLE
Add Message#isRickRoll

### ISSUE THREAD

**Issue by natanbc** [mewna/catnip#214]
Since discord added the spoilers feature, a lot of innocent users are being made victims of a terrible fate called rickroll. It consists of a message containing [this horrible torture]( https://www.youtube.com/watch?v=dQw4w9WgXcQ ) being sent in a spoiler, leading to the horrible fate of being rickrolled for anyone who clicks it. This feature is needed to ensure the safety of discord users.

**Comment by queer** [comment]
Will this only detect dQw4, or other variations?

**Comment by xaanit** [comment]
We also need a check to see if you [you've been gnomed.](https://youtube.com/watch?v=6n3pFFPSlW4)

**Comment by natanbc** [comment]
`CompletionStage<Boolean> isRickRoll()` and `CompletionStage<Boolean> isGnome()`

They call into a third party database of rickroll and gnome urls

**Comment by queer** [comment]
Distribute the database with the lib as a data.json :^)

**Comment by natanbc** [comment]
@Kodehawa is an expert in json flat file storage, he can help us

**Comment by queer** [comment]
To be serious, if we could do it in a relatively small / non-perf/size-impacting way I'd totally merge a PR for this just for memes

**Comment by natanbc** [comment]
It also must follow redirects

**Comment by xaanit** [comment]
I think for efficiency sake it should just be loaded into `Map<String, SpoilerTrollType>` on startup where it's, as an example, `map.put("6n3pFFPSlW4", SpoilerTrollType.GNOME);`

**Comment by queer** [comment]
Could work, as long as we can follow redirects and not get trapped in a redirect loop

**Comment by xaanit** [comment]
Maybe a max of 5 redirects? Or just keep track of where you've been before, and if you go back exit.

**Comment by SamOphis** [comment]
This is a perfect issue for the Extremely Experienced Enterprise Level Oracle Java and JetBrains Kotlin Software Junior Engineer SamuelOphis. I believe I can handle this, my friends.
