### ISSUE TITLE
Can't deserialize certain nested entities

### ISSUE THREAD

**Issue by napstr** [mewna/catnip#219]
Some nested entities have more than a single implementation, and neither can Jackson know which should be deserialized, not can we add a `JsonDeserialize` annotation as a hint.

Example: AuditLogEntry and its OptionalEntryInfo, where OptionalEntryInfo has several implementations.

**Comment by queer** [comment]
Fixed by #221

**Comment by napstr** [comment]
Reopen pl0x this was not solved by #221.

#221 solved #218

**Comment by DRSchlaubi** [comment]
Also `Channel objects can't get deserialized` and you can't really find out which type of channel it is because there is no type variable in any channel object

**Comment by queer** [comment]
Oops

**Comment by DRSchlaubi** [comment]
Should we completly remove toJson and fromJson methods or should we keep it?

**Comment by queer** [comment]
It really depends on how we want to deal with it. My bot relies on some form of serialization existing (for sharing data / sending it over a message bus), but I'm not opposed to doing a different method than Entity#toJson/fromJson

**Comment by napstr** [comment]
We probably gucci, adding `@JsonTypeInfo(use = JsonTypeInfo.Id.MINIMAL_CLASS)` on selected interfaces that have multiple impls is good enough so far in tests.

**Comment by DRSchlaubi** [comment]
Adding the Annotation wouldn't always deserialize with the needed entity, right?
