### ISSUE TITLE
MessageBuilder and MessageOptions merge.

### ISSUE THREAD

**Issue by Kodehawa** [mewna/catnip#222]
MessageBuilder and MessageOptions currently do similar stuff, but they're on a separate class.

For example: you can't send an attachment using MessageBuilder, but you can using MessageOptions. Though, you can, for example, send an embed or a simple message with both.

Seeing as both want to accomplish the same thing, both should be merged into MessageBuilder.

**Comment by queer** [comment]
@SamOphis pls fix

**Comment by queer** [comment]
@SamOphis this is your bad api design plz fix or you're blocked from the repo forever

**Comment by queer** [comment]
@SamOphis smh kotlin users not even fixing the issues they created it's been a week you nerd smhing my head at you

**Comment by queer** [comment]
Fixed in #248 #249
