### ISSUE TITLE
MESSAGE_DELETE discord payload returns channel_id, while catnip implementation doesn't provide it.

### ISSUE THREAD

**Issue by Kodehawa** [mewna/catnip#223]
Basically, on `DiscordEvent.MESSAGE_DELETE` there's no message.channel() method, even though discord provides the id of it.

Ref.: 
![image](https://user-images.githubusercontent.com/20606963/52190162-47c81100-281c-11e9-9259-d8fb043f8c39.png)

**Comment by Kodehawa** [comment]
For clarification: this is for the convenience methods `guild()` and `channel()`, not the ids.

**Comment by queer** [comment]
Kode was a good bean who fixed this in #224, instead of PRing more broken code like @SamOphis
