### ISSUE TITLE
Consider moving guild event dispatches off of the main event loop threads

### ISSUE THREAD

**Issue by queer** [mewna/catnip#227]
Could probably just deploy a [worker verticle](https://vertx.io/docs/vertx-core/java/#worker_verticles) per shard spawned (to handle cache? end-user dispatches? buffering?)? That way we can avoid blocking the main event loop threads and help keep the shard lifecycle stay alive.

**Comment by queer** [comment]
I just realized - vert.x will ensure that an event of a given type is always fired on the same event loop thread, ie. all shards will send events of the same type to the same thread. This seems like a terrible idea.

**Comment by SamOphis** [comment]
SamOphis agrees with that statement, Miss Queer Amy Null. I believe Vert.x, the software sponsored by the Eclipse Development Team, is very doubtful in some places! Hah! Yes, indeed so.

**Comment by queer** [comment]
Will be done in v2
