### ISSUE TITLE
Make a better event bus than the built-in vert.x one

### ISSUE THREAD

**Issue by queer** [mewna/catnip#254]
Example need for this:

Suppose you run a vert.x-cluster of catnip bots, using in-memory caching. The vert.x event bus might send events to ANY member of the cluster, which is likely to cause issues with caches not being "coherent" (so to speak) across all members of the cluster, thereby causing :boom:

**Comment by Stupremee** [comment]
Probably use the Guava Event Bus

**Comment by queer** [comment]
No.

**Comment by Stupremee** [comment]
Why?

**Comment by queer** [comment]
I dislike it significantly.

- Forces you to use annotations
- Can only fire a single object over it, otherwise you have to wrap things in objects (see ex #157) and that'd be a bit annoying from the end-user perspective unless we did even more of our own internal wrapping
- We're likely moving to Java-11-only, meaning that our only use for Guava (ImmutableX.of/copyOf) becomes unnecessary because of the J9+ collection factory methods
- Guava event bus allows wildcard listeners, which might violate our attempts to enforce type-safety (yes, vert.x event bus bad etc etc etc, but we wanna move away from it for a REASON)
- Minor nitpick that the Guava EventBus register/post methods take an Object and don't do a type param (mostly just personal preference at that point tho)
- Guava event bus uses reflection to dispatch events, which does have a performance penalty
- Probably more but I can't be bothered to keep listing reasons

**Comment by Stupremee** [comment]
Oh okay

**Comment by Stupremee** [comment]
What about https://projectreactor.io/ ?

**Comment by queer** [comment]
This has been discussed extensively in the catnip server afaik, and we don't want to use ProjectReactor because

- don't want to force using their specific implementation of reactive streams (ex. what if I prefer using Rx-style?)
- Scala + Reactor = lol

**Comment by Stupremee** [comment]
Okay xD

**Comment by SamOphis** [comment]
Fun fact Vert.x supports Kotlin coroutines!!!!!!! Amazing right!?!?!?!?!?!?!?!?!
I bet that's something you'll want to

**react**

to

**Comment by queer** [comment]
Related to #157

**Comment by queer** [comment]
See #326
