### ISSUE TITLE
Get rid of fluent accessors

### ISSUE THREAD

**Issue by alula** [mewna/catnip#279]
Maybe they make code a bit more readable in Java but:

- JavaBeans convention is de facto standard
- They break inspections, eg. [IDEA null checks](https://cdn.discordapp.com/attachments/512759976373256232/559796272983310387/unknown.png) because tooling doesn't know that some methods are accessors.
- [Kotlin](https://kotlinlang.org/docs/reference/properties.html)/[Groovy](http://groovy-lang.org/style-guide.html#_getters_and_setters)/JavaScript/(anything else) users take no advantage of properties/field-like access.

**Comment by queer** [comment]
./shrug, it'd be a massive breaking change at this point. It's been discussed extensively in Discord afaik, and the gist of it is that we stick with it because vert.x does; I'd probably care more about doing this if/when(?) we move away from using vert.x. I'm not opposed to this, just don't think that it's worth caring aobut this now when there's bigger issues to fix.

**Comment by SamOphis** [comment]
agreed with @queer.
- consistency
- appearance (fluent is better don't @ me)
- massive breaking change

**Comment by queer** [comment]
#277 is relevant I think

**Comment by SamOphis** [comment]
advantages for javabeans:
* standardized
* supported and even expected by many tools/services
* very popular
* very clear what the methods actually do

advantages for fluent as of 1.x:
* matches other libraries (vert.x)
* looks much much much better than JavaBeans
* already used extensively throughout the entirety of the lib

if we switch to JavaBeans, we get more standardized code which is supported more as well as more clarity, but we also have to rewrite the vast majority of the library. not only that, setters in javabeans aren't supposed to return `this` which makes the clean, simple and concise code of current catnip a lot more bloated

**Comment by queer** [comment]
> advantages for fluent as of 1.x:
- Most of it is just changing a single lombok annotation (`@Accessors(fluent = true)` to just `@Accessors`)
- Subjective
- True

Also, as I understand it, the JavaBeans convention is just a *naming* convention -- I haven't seen anything dictating that setters must be `void`

**Comment by KJP12** [comment]
Seeing as delombok, git and the aid of IntelliJ can actually make the process quick, just delombok the file, rename the variables to the javabeans convention then just reverting the file then changing the annotations, someone could do this really quickly.
