### ISSUE TITLE
Dumb feature idea: Let users plug in custom EntityBuilders

### ISSUE THREAD

**Issue by queer** [mewna/catnip#314]
Questions:
- What kind of interface would `EntityBuilder` have?
- How to "inject" it?
- Do we mess with method signatures (ie. `List<Role> roles()` -> `<T extends Role> List<T> roles()` sort of thing) to avoid a lot of casting?
- Should the default `EntityBuilder` be non-`final` to allow for users to extend it to have a non-terrible time of implementing?

**Comment by Stupremee** [comment]
Would definitely make sense. But then it would be best to use an interface. You could inject it via the CatnipOptions and then simply access it from the Catnip class.

**Comment by queer** [comment]
Yeah that's basically the idea; just having the default implementation be non-final so that you can extend it to avoid implementing everything yourself.

**Comment by queer** [comment]
Closed in 93421fac.
