### ISSUE TITLE
Convert chunk re-requesting to allow user-controlled handling

### ISSUE THREAD

**Issue by queer** [mewna/catnip#341]
Basically, when we run into a situation where we might want to re-request member chunking, rather than handling it automatically at the lib level, it might be worth just converting it to just emit an event and let the end-user handle it however they want.

**Comment by SamOphis** [comment]
Just like the other events, I think it'd be a much better experience to keep this optional. Users shouldn't have to deal with this from a Discord Library unless they explicitly enable it imho as it makes startup more complex and scares new users more

Not just that, if they don't implement chunking properly themselves, it's gonna lead to the rest of the library acting as if the members were re-requested despite the opposite happening

**Comment by queer** [comment]
This will be added in v2; see #326.

**Comment by queer** [comment]
Added in v2 branch
