### ISSUE TITLE
Converting (some) log messages to lifecycle(?) events instead

### ISSUE THREAD

**Issue by queer** [mewna/catnip#342]
One thing that I've been considering lately is, instead of logging a bunch of stuff like catnip does now, it could instead emit lifecycle(? maybe a new type?) events. For example, we log when a shard gets an OP 9. I'm proposing that we add a config option that will make it emit a "shard received OP 9" event instead of logging that it received an OP 9. This would be an **opt-in** change, ie. you would have to specifically choose to enable this functionality. See also @SamOphis' comments on #341.

**Comment by SamOphis** [comment]
+1 for this, will there be a complete list of log events soon?

**Comment by queer** [comment]
Yep, just working on figuring out what all I want to convert to this sort of "format." Open to suggestions.

**Comment by SamOphis** [comment]
Sounds 🔥, I think there should be events for sockets closing with codes and reasons, the session being invalidated, resumed (if you don't already emit this), if an entry is expected in cache but isn't, rate limits being hit, and a shard identifying

**Comment by SamOphis** [comment]
Clarification on sockets closing, I meant the 4xxx codes more than anything but I guess it is applicable to all codes

**Comment by queer** [comment]
This will be added in v2; see #326.

**Comment by queer** [comment]
Added in v2 branch
