### ISSUE TITLE
NumberFormatException on messages with mentioned roles

### ISSUE THREAD

**Issue by SamOphis** [mewna/catnip#363]
Issue arises when you send a message which 1. mentions a role in content and 2. has embed content, not sure if the last step even matters

Sentry Issue: [here](https://sentry.io/share/issue/426cf301af884c1294a5e4ab82ddf964/) (includes stack trace)
Line of Code responsible: [here](https://github.com/mewna/catnip/blob/master/src/main/java/com/mewna/catnip/cache/EntityCache.java#L263)

It appears that catnip is trying to parse a long but one of the parameters its providing to that method isn't a valid long

**Comment by queer** [comment]
Forgot to respond to this when it was made, oops. This was fixed in v2 in commit 6712e50ab5237143f45e90354731a974989ef927 and will be released as such.

**Comment by SamOphis** [comment]
Thank you I'll switch when v2 becomes stable/the recommended or default branch
