### ISSUE TITLE
PUBLIC guild feature

### ISSUE THREAD

**Issue by queer** [mewna/catnip#387]

**Comment by queer** [comment]
Replaces LURKABLE https://github.com/discordapp/discord-api-docs/issues/1117#issuecomment-533757618

**Comment by queer** [comment]
Fixed in decd9f5a

**Comment by Jump-Suit** [comment]
![image](https://user-images.githubusercontent.com/26616362/65370828-a5319680-dc22-11e9-8e75-6cc5283b47a5.png)

Do you consider these also deprecated? Curious... As Commerce is still very much alive... (Game Dev here who has Server Commerce)
