### ISSUE TITLE
MEMBER_LIST_DISABLED feature flag

### ISSUE THREAD

**Issue by queer** [mewna/catnip#392]
Supposedly came into existence the other day?

**Comment by Bowser65** [comment]
This feature flag is enabled in the Fortnite server, and to a big surprise to everyone it makes the client not render the list of members. The client doesn't seem to receive any presence data, as everyone is showing offline for me in the FN server.

![image](https://user-images.githubusercontent.com/9999055/66723399-eaf41000-ee18-11e9-8e3b-d5a6b2c7d3fc.png)

**Comment by queer** [comment]
Closed in 76d3fc9
