### ISSUE TITLE
~8 seconds delay between adding reactions

### ISSUE THREAD

**Issue by Vaerys-Dawn** [mewna/catnip#448]
Issue: When adding multiple reactions to a message there is a massive delay between adding the first and second reactions.

Expected behaviour: Reactions are added in semi quick succession. 
example: https://i.imgur.com/zJT3TMv.gifv

Actual behaviour: Bot takes about ~8 seconds to apply a second reaction
example: https://i.imgur.com/H0wSzUv.gifv

Relevant code:
```
msg.channel().addReaction(msg.id(), Constants.SNAIL);
msg.channel().addReaction(msg.id(), Constants.LETTUCE);
```

**Comment by queer** [comment]
Thanks for the report! Unfortunately, I am [unable to reproduce this locally](https://imgur.com/a/aK8RW0T). 

Can you:
- Tell me what custom options you have set, if any? In particular, I'm interested in whether you're using a custom requester / ratelimiter or not. The rest of the questions will assume you're not.
- Tell me whether you're using the serial requester or the burst requester (or if it's just not specifically configured by you)?
- Tell me whether you have `CatnipOptions#restRatelimitsWithoutClockSync` enabled?
- Enable trace logs for `com.mewna.catnip.rest.ratelimit.DefaultRateLimiter` and `com.mewna.catnip.rest.requester.AbstractRequester`, so I can see the request timings?
