### ISSUE TITLE
Allow getting raw JSON responses from REST methods

### ISSUE THREAD

**Issue by queer** [mewna/catnip#47]
Could probably just do `XAsJson` variants or similar, eg. `createMessageAsJson`, but that sort of naming may be misleading.

**Comment by natanbc** [comment]
Maybe have methods as both `X` and `XRaw`

**Comment by queer** [comment]
Sounds good to me :+1:

**Comment by queer** [comment]
If we do this, then the `X` methods can just call the `XRaw` methods and apply some stuff to the future I think, which is nice.

**Comment by natanbc** [comment]
> then the `X` methods can just call the `XRaw` methods and apply some stuff to the future

Basically the same as we do for [paginated endpoints](https://github.com/mewna/catnip/blob/8419688255ebc7f6f04c17bdfe6280f6f4bdd5ef/src/main/java/com/mewna/catnip/rest/handler/RestUser.java#L74-L117)
