### ISSUE TITLE
Javadocs 404 error issue

### ISSUE THREAD

**Issue by TheChilliPL** [mewna/catnip#475]
![image](https://user-images.githubusercontent.com/18823939/92757490-13b8b880-f38e-11ea-9d3b-64ce05332f92.png)
Go to https://mewna.github.io/catnip/docs/, search for `getGuild`, click the first result. It gives a 404 page.
Happens for other search queries too

**Comment by queer** [comment]
🤔 Thanks Javadocs. I’ll check it out soon, thanks for the report!

**Comment by queer** [comment]
This should be fixed now; feel free to re-open this or open a new issue if it breaks again ^^;
