### ISSUE TITLE
Not able to get mentioned channels from MESSAGE_CREATE type of event

### ISSUE THREAD

**Issue by Praytic** [mewna/catnip#509]
I tried to get mentioned channels from the message like that `Message#mentionedChannels()`, however I got empty list. So when I debugged this, I found out that catnip is looking for `mention_channels` that doesn't exist in MESSAGE_CREATE type.

**Comment by queer** [comment]
This is not a bug; see the relevant section of the Discord API docs https://discord.com/developers/docs/resources/channel#message-object The catnip documentation about this could definitely be improved tho

**Comment by Praytic** [comment]
Got it, thanks.
