### ISSUE TITLE
Support APIv9

### ISSUE THREAD

**Issue by queer** [mewna/catnip#538]
https://github.com/discord/discord-api-docs/pull/2855

**Comment by queer** [comment]
Wow, this is a large set of changes. Initial list of changes:

- [ ] Set default API version to 9.
- [ ] Create a new channel type, `ThreadChannel` which extends `MessageChannel`. TODO: Are there guild *and* non-guild threads? That will affect the implementation a lot.
  - [ ] Add `message_count`, `member_count`, and `member`. These are currently only used for threads, but are exposed on the top-level channel object for potential future use. 
  - [ ] Add `thread_metadata` for threads. Should have helpers to expose the higher-level objects.
  - [ ] Channel types 10 `NEWS_THREAD`, 11 `PUBLIC_THREAD`, and 12 `PRIVATE_THREAD`.
  - [ ] Track active threads from `GUILD_CREATE` in a new active thread cache.
  - [ ] Cache `ThreadMember`s separately from `ThreadChannel`s?
- [ ] Sane limit checking.
- [ ] Update the `Message` object with new thread-related fields.
  - [ ] Hydrate a `Thread`(`ThreadChannel`?) object where possible.
  - [ ] Add message types 18 `THREAD_CREATED` and 21 `THREAD_STARTER_MESSAGE`.
  - [ ] Add message flag `1 << 5` `HAS_THREAD`.
- [ ] Update intents with thread-related events.
  - [ ] `GUILDS`: `THREAD_CREATE`, `THREAD_UPDATE`, `THREAD_DELETE`, `THREAD_LIST_SYNC`, `THREAD_MEMBER_UPDATE`, `THREAD_MEMBERS_UPDATE`.
  - [ ] `GUILD_MEMBERS`: `THREAD_MEMBERS_UPDATE`.
  - [ ] Document different information sent in `THREAD_MEMBERS_UPDATE` depending on intents.
  - [ ] Verify whether threads work in DMs...
- [ ] Add new JSON error codes:
  - [ ] 50083
  - [ ] 50084
  - [ ] 50085

**Comment by queer** [comment]
Threads are confirmed guild-only and aren't expected to be available in DMs without another major API version bump, see https://canary.discord.com/channels/613425648685547541/837051880982577223/837913346568749087

**Comment by queer** [comment]
https://github.com/discord/discord-api-docs/pull/2875

**Comment by queer** [comment]
#543?

**Comment by Lulalaby** [comment]
Wow, you're fast

**Comment by queer** [comment]
I try.

**Comment by Lulalaby** [comment]
not bad queer <3
