### ISSUE TITLE
Figure out how to deal with all the garbage that gets created (basically just memory golfing)

### ISSUE THREAD

**Issue by queer** [mewna/catnip#99]
From testing it on a relatively-large (>30 recommended shards) bot, it seems that we're quite wasteful with RAM to an extent - wasting ~300MB of RAM that gets GC'd quite often

**Comment by natanbc** [comment]
I'm guessing most of that data comes from the buffers we allocate to decompress websocket payloads. We could probably keep a pool of them (IIRC vertx buffers use unpooled `ByteBuf`s by default), but I'm not sure how effective this would be (aka needs testing).

**Comment by queer** [comment]
Closing this since #113 was merged
